[함헌규] sprint4
codeit-sprint-fullstack/3-sprint-mission-fe pull request #65
Opened 2024-10-14 02:24 UTC by heonq

# 요구사항

## 기본 요구사항

### 공통

- [x] Github에 스프린트 미션 PR을 만들어 주세요.

- [x] 'https://sprint-mission-api.vercel.app/articles' API를 이용하여 아래 함수들을 구현해 주세요.

- [x] getArticleList() : GET 메서드를 사용해 주세요.
- [x] page, pageSize, keyword 쿼리 파라미터를 이용해 주세요.
- [x] getArticle() : GET 메서드를 사용해 주세요.
- [x] createArticle() : POST 메서드를 사용해 주세요.
- [x] request body에 title, content, image 를 포함해 주세요.
- [x] patchArticle() : PATCH 메서드를 사용해 주세요.
- [x] deleteArticle() : DELETE 메서드를 사용해 주세요.
- [x] fetch 혹은 axios 를 이용해 주세요.

- [x] 응답의 상태 코드가 2XX가 아닐 경우, 에러메시지를 콘솔에 출력해 주세요.
- [x] .then() 메서드를 이용하여 비동기 처리를 해주세요.

- [x] .catch() 를 이용하여 오류 처리를 해주세요.

- [x] 'https://sprint-mission-api.vercel.app/products' API를 이용하여 아래 함수들을 구현해 주세요.

- [x] getProductList() : GET 메서드를 사용해 주세요.
- [x] page, pageSize, keyword 쿼리 파라미터를 이용해 주세요.
- [x] getProduct() : GET 메서드를 사용해 주세요.
- [x] createProduct() : POST 메서드를 사용해 주세요.
- [x] request body에 name, description, price, tags, images 를 포함해 주세요.
- [x] patchProduct() : PATCH 메서드를 사용해 주세요.
- [x] deleteProduct() : DELETE 메서드를 사용해 주세요.
- [x] async/await 을 이용하여 비동기 처리를 해주세요.

- [x] try/catch 를 이용하여 오류 처리를 해주세요.

- [x] 구현한 함수들을 아래와 같이 파일을 분리해 주세요.

- [x] export를 활용해 주세요.
- [x] ProductService.js 파일 Product API 관련 함수들을 작성해 주세요.
- [x] ArticleService.js 파일에 Article API 관련 함수들을 작성해 주세요.
- [x] 이외의 코드들은 모두 main.js 파일에 작성해 주세요.

- [x] import를 활용해 주세요.
- [x] 각 함수를 실행하는 코드를 작성하고, 제대로 동작하는지 확인해 주세요.

## 주요 변경사항
- article,product 관련 api 구현

## 멘토에게
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-10-14 02:30 UTC, heonq commented on assets/scripts/main.js
만약 에러가 발생하면 각 동작별로 에러처리가 필요하다고 생각해서 함수를 실행할 때마다 catch하도록 작성했습니다. 적절한 방식인지 궁금합니다!

2024-10-16 06:14 UTC, kimjong95 requested changes
적절히 분리된 형태로 코드를 작성해주신 것 같습니다.

코드에서 Promise/then 문법으로 비동기처리를 구성해주고 계신데 가독성이 떨어지기도하고 사용하기 불편한 느낌이 드셨을수 있을것 같아요.
현재는 좀더 현대화된 async/await 방식으로 비동기처리를 해주고 있습니다. 이는 콜백지옥을 벗어나게도 해주며 좀더 선언적인 코드관리를 도와줍니다.

package.json을통해서 의존성을 설치해주신 위치가 적절한것이 좋았습니다. 의존성의 설치 위치는 프로젝트 루트로부터 설치해주시는게 좋습니다. 
(다만 이후에 모노레포 구조에 모듈화 구조에서는 조금 다를 수도 있긴 합니다!)

Request changes형태로 리뷰를 마치겠습니다. 코멘트 확인해주시고 수정사항 반영해주시면 좋을 것 같습니다!

2024-10-16 06:14 UTC, kimjong95 commented on assets/scripts/apis/ArticleService.js
> +export const getArticleList = (page = 1, pageSize = 100, keyword = "") => {
`ProductService`쪽에는 잘 작성해주셨지만 여기는 `async`가 누락된것 같습니다!

2024-10-16 06:14 UTC, kimjong95 commented on assets/scripts/apis/ArticleService.js
> +const handleResponse = (apiMethod) => {
`parameter`로받은 메서드의 `response`형태로 bypass하는 함수라 함수사용에 의미가 있는지 확인이 필요할 것 같아요.

2024-10-16 06:14 UTC, kimjong95 commented on assets/scripts/apis/ArticleService.js
> +  return data;
(사소)

```diff
- const data = handleResponse(api.get(URL));
- return data;
+ return handleResponse(api.get(URL));
```

2024-10-16 06:14 UTC, kimjong95 commented on assets/scripts/apis/ArticleService.js
> +  const URL = `${URLS.articles}?page=${page}&pageSize=${pageSize}&keyword=${keyword}`;
GET방식으로 url파라미터를 직접 붙혀주셔도(혹시 paramsSerializer 에 대한 고민이 있으셨나? 싶어요) 좋지만 객체형태의 params로 넘겨주는 방식도 있습니다. 가독성이 더 좋아질 수 있을것 같아요.

2024-10-16 06:14 UTC, kimjong95 commented on assets/scripts/apis/ProductService.js
> +export const getProductList = async (page = 1, pageSize = 100, keyword = "") => {
이렇게 파라미터를 여러개 사용하는 함수는 위에 주석으로 함수에 대한 설명을 해주시면 좋을것 같습니다. JSDoc이라는 주석방식이 있는데요 다음과 같이 사용할 수 있습니다.

```
/**
 *
 * @param {number} page 조회할 페이지번호입니다.
 * @param {number} 한번에 조회로 가져오는 응답값의 개수입니다.
 * @param {string} keyword keyword를 통해 검색을 할 수 있습니다
 * @return {Promise<response>} 비동기로인한 Promise로 productList들을 리턴합니다.
 */
export const getProductList = async (page = 1, pageSize = 100, keyword = "") => {
  ...
}

```
그리고 사용처에서 함수에 마우스오버를 해보시면 함수의 인터페이스와 설명들이 노출됩니다. 
함수 또는 객체에대한 스펙을 주석으로 설명해주시면서 협업하는 개발자들에게 휴면에러를 줄여줄 수 있는 이 방법은 주석을 사용하는 가장 좋은 방법 중 하나입니다.

2024-10-16 06:14 UTC, kimjong95 commented on assets/scripts/main.js
헌규님이 설명해주신 것 처럼 함수에서 발생하는 에러별로 catch하는 방식이 다를 수 있습니다. 다만 모든 에러를 사용처마다 처리해줄 수도 없겠죠? 상황에따라 사용처에서할지, 공통으로할지는 판단이 필요할 수 있습니다.

현업에서는 에러처리를 모듈화해서 제공하기도 합니다. 적절한 에러끼리 그룹화하고 서비스에 크리티컬한 에러인지, 에러가 발생해도 서비스제공에 문제가 없는지 등으로 구분할 수 있겠죠.

2024-10-16 06:14 UTC, kimjong95 commented on assets/scripts/main.js
> +    console.error(DOCUMENT_ERROR_MESSAGES.failCreatingDocument, e.message);
여기서는 테스트목적이었겠지만,
에러가 발생했을때는 콘솔에 에러를 노출하고 끝나면 안됩니다!! 반드시 상위로 에러를 throw 해주어야하고 그 에러를 catch하는 적절한 상위모듈에서 반드시 처리가 필요합니다.

2024-10-16 06:14 UTC, kimjong95 commented on assets/scripts/main.js
> +  console.table(
로깅방식이 좋습니다! console api에는 다양한 사용법이있는데 table은 콘솔을 구조화해서 보여주기 좋은 방식입니다.

2024-10-16 06:14 UTC, kimjong95 commented on assets/scripts/apis/common.js
> +import axios from "axios";
axios 인스턴스를 초기화하는 로직이 존재하네요!
그렇다면 파일이름에 대한 고민이 필요할 것 같아요. common이라는 파일이름은 적절하지 않을 것 같습니다.

2024-10-17 15:07 UTC, heonq commented on assets/scripts/apis/common.js
> +import axios from "axios";
axiosInstance.js로 변경했는데 적절할까요?!

2024-10-17 15:17 UTC, heonq commented on assets/scripts/main.js
> +    console.error(DOCUMENT_ERROR_MESSAGES.failCreatingDocument, e.message);
console.error가 아닌 에러를 처리하는 코드를 이 catch문 안에 작성하면 되는 걸까요?!

2024-10-22 00:29 UTC, kimjong95 commented on assets/scripts/main.js
> +    console.error(DOCUMENT_ERROR_MESSAGES.failCreatingDocument, e.message);
넵 해당애러를 처리할수 있도록 코드를 작성해주면 되고, 이 에러는 사용처마다 다르게 처리될 수 있기에 해당 API를 처리하는곳 에서 try/catch를 선언해주시고 성공했을때, 실패했을때를 해당함수에서 받아 사용할 수 있게 처리하는게 일반적인 방식입니다.
예를 들어보자면 두가지 방식이 있을수 있을것 같아요
(예시로인해 과도한 코드가 포함됨)


```
// callback으로 처리
// 선언부
const getArticle = async (id, callbackSuccess, callbackError) => {
  const URL = `${URLS.articles}/${id}`;
  return api.get(URL).then((response) => callbackSuccess(response.data)).catch((error)=> callbackError(error));
};

// 사용처
const { articleList, isSuccess } = getArticle('id', onSucess, onError);
```

```
// 사용처에서 처리
// 선언부
const getArticle = async (id) => {
  const URL = `${URLS.articles}/${id}`;
  return api.get(URL).then((response) => return { isSuccess: true, data: response.data }).catch((error)=> return { isSucess: false, data: null, error });
};

// 사용처
const { isSuccess, data, error } = getArticle('id');
if(isSucess) {
    onSucess(data);
} else {
    onError(error);
}
```

2024-10-22 00:31 UTC, kimjong95 approved these changes

2024-10-23 11:24 UTC, merged